### ISSUE TITLE
The "increase_fps" option causes a videoless playback on some configuration of libav.

### ISSUE THREAD

**Issue by persmule** [m13253/BiliDan#22]
When using bilidan with default option, along with mpv provided by debian testing, mpv tells me:

[stream] Video (+) --vid=1 (h264)
[stream] Audio (+) --aid=1 (aac)
[stream] Subs  (+) --sid=1 'tmp-danmaku2ass-w498a9_7.ass' (ass) (external)
Opening video filter: [lavfi graph=fps=fps=60:round=down]
AO: [pulse] 48000Hz stereo 2ch float
[libav] fps: No such option: round.
[libav] AVFilterGraph: Error initializing filter 'fps' with args 'fps=60:round=down'
[lavfi] Can't configure libavfilter graph.
Video filter chain:
 [vd] 640x480 yuv420p Autoselect/Autoselect CL=1
 [in] 640x480 yuv420p BT.601 (SD)/TV CL=1
 [lavfi] 640x480 yuv420p BT.601 (SD)/TV CL=1   <---
 [out] ???
Cannot initialize video filters.
Could not initialize video chain.

and leaves me a videoless playback. Now I have to disable "increase_fps" in the source code.

**Comment by m13253** [comment]
BiliDan does not support libav, since libav lacks behind FFmpeg's development pace for years.

I have said in Readme that, FFmpeg is depended instead of libav.

See https://github.com/mpv-player/mpv/wiki/FFmpeg-versus-Libav for details.

You have two options:

1. patch BiliDan yourself and disable increase_fps

2. just turn on hardware decoding with `--mpvflags="--hwdec=vaapi (or vdpau)"`, increase_fps will be automatically turned off.

**Comment by m13253** [comment]
Fixed in 8c9b73372a8a6ad4510dc0287e2ef20dc4658001.
Use `--keep-fps` to disable increase_fps.

P.S. Again, the use of libav is discouraged. It will be better if you can upgrade your Debian to use the latest FFmpeg.
